/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    PrismaButton: typeof import('./src/components/PrismaButton/PrismaButton.vue')['default']
    PrismaButtonElement: typeof import('./src/components/PrismaButtonElement/PrismaButtonElement.vue')['default']
    PrismaButtonVuetify: typeof import('./src/components/PrismaButtonVuetify/PrismaButtonVuetify.vue')['default']
  }
}
